language: csharp
mono: none
dotnet: 2.1.500
solution: RippLib.Util.sln
script:
  - dotnet restore
  - dotnet build -c Release
  - dotnet test RippLib.Util.sln
  - dotnet pack ./RippLib.Util/obj/Release/RippLib.Util.*.nuspec
  - dotnet setApiKey $NUGET_API_KEY -Source $NUGET_SOURCE -Verbosity quiet
  - dotnet push RippLib.Util.*.nupkg -Source $NUGET_SOURCE
