# safelist
branches:
  only:
  - master
language: csharp
mono: 5.16.0
dotnet: 2.1.500
solution: RippLib.Util.sln
install:
  - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono nuget.exe restore RippLib.Util.sln
script:
  - dotnet restore
  - msbuild /p:Configuration=Release RippLib.Util.sln
  - dotnet build ./RippLib.Util.Tests/RippLib.Util.Tests.csproj -c Release
  - dotnet test ./RippLib.Util.Tests/RippLib.Util.Tests.csproj
  - mono nuget.exe pack ./RippLib.Util/obj/Release/RippLib.Util.*.nuspec
  - mono nuget.exe setApiKey $NUGET_API_KEY -Source $NUGET_SOURCE -Verbosity quiet
  - mono nuget.exe push RippLib.Util.*.nupkg -Source $NUGET_SOURCE