language: csharp
mono: none
dotnet: 2.1.500
solution: RippLib.Util.sln
install:
  - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono nuget.exe restore RippLib.Util.sln
script:
  - dotnet restore
  - msbuild /p:Configuration=Release RippLib.Util.sln
  - dotnet test RippLib.Util.sln
  - dotnet pack ./RippLib.Util/obj/Release/RippLib.Util.*.nuspec
  - dotnet setApiKey $NUGET_API_KEY -Source $NUGET_SOURCE -Verbosity quiet
  - dotnet push RippLib.Util.*.nupkg -Source $NUGET_SOURCE
