language: csharp
mono: 5.16.0
dotnet: 2.1.500
solution: RippLib.Util.sln
install:
  - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono nuget.exe restore RippLib.Util.sln
script:
  - dotnet restore
  - msbuild /p:Configuration=Release RippLib.Util.sln
  - dotnet build ./RippLib.Util.Tests/RippLib.Util.Tests.csproj -c Release
  - dotnet test ./RippLib.Util.Tests/RippLib.Util.Tests.csproj
  - dotnet pack ./RippLib.Util/RippLib.Util.csproj
  - dotnet nuget push RippLib.Util/bin/Release/RippLib.Util.*.nupkg -k $NUGET_API_KEY -s $NUGET_SOURCE